# Generated by Django 3.0.2 on 2020-01-15 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wizards_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wizard',
            name='house',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='wizards_api.House'),
        ),
    ]
