# Generated by Django 4.0.1 on 2022-01-13 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='founder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app.founder'),
        ),
        migrations.AlterField(
            model_name='wizard',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
