# Generated by Django 4.0.1 on 2022-01-13 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_house_founder_alter_wizard_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='founder',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='house',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
